[package]
name = "ultimate_data_arc"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = "2018"

[dependencies]
zstd = "0.4"
byteorder = "1"
scroll = "0.9"
scroll_derive = "0.9"
failure = "0.1"
hexdump = "0.1"
crc = "1"
